config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: "users/registrations" },
             path_names: { sign_up: "" }

  root to: "home#home"
  get "random", to: "home#random_profile", as: :random_profile

  namespace :admin do
    resources :instructor_profiles, only: :index
    resources :class_types, except: [:show, :destroy], controller: :clazz_types
    resources :studios, except: [:show, :destroy]
    resources :studio_brands, except: [:show, :destroy]
    resources :studio_brand_studios, only: [:create, :destroy]
    resources :class_templates, except: [:show, :destroy]
    resources :class_template_class_types, only: [:create, :destroy]
    resources :invitations, only: [:index, :new, :create]
    resources :newsletter_signups, only: :index
    resource  :landing_page, only: [:edit, :update], controller: :landing_page
    resource :ghosting_session, only: [:create, :destroy]
  end

  resources :classes, only: [:show, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member

    resource :change, controller: :class_changes, only: [] do
      post :cancel
      post :uncancel
      post :substitute
      post :unsubstitute
      post :delete
      post :delete_and_future_weeks
    end
  end

  resources :recurring_classes, only: [:index, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member
  end

  resources :instructor_profiles, except: :destroy do
    get :welcome, on: :collection
    get :profile_photo
  end

  namespace :instructor_profile do
    resource :profile_photo, only: :edit
    resource :cover_photo, only: :edit
    resource :social_ids, only: :edit
  end

  resource :class_templates_by_studio, only: :show, controller: :class_templates_by_studio
  resource :duration_by_class_template, only: :show, controller: :duration_by_class_template

  resources :newsletter_signups, only: [:new, :create]
  resources :got_its, only: :create

  resource :search, only: :show, controller: :search

  get :faq, to: "home#faq", as: :faq

  get "robots.txt", to: "robots#show", controller: :robots

  get "/:id", to: "instructor_profiles#show", as: :profile
end

app/controllers/admin/clazz_types_controller.rb
class Admin::ClazzTypesController < Admin::ControllerBase
  before_action :find_clazz_type, only: [:edit, :update]

  def index
    @clazz_types = ClazzType.order(name: :asc).decorate
  end

  def new
    @clazz_type = ClazzType.new
  end

  def edit
    @clazz_type = @clazz_type.decorate
  end

  def create
    @clazz_type = ClazzType.new create_params
    if @clazz_type.save
      flash[:success] = "Class type created"
      redirect_to admin_class_types_path
    else
      render :new
    end
  end

  def update
    if @clazz_type.update_attributes create_params
      flash[:success] = "Class type saved"
      redirect_to admin_class_types_path
    else
      render :edit
    end
  end

  private

  def find_clazz_type
    @clazz_type = ClazzType.find_by id: params[:id]
    if @clazz_type.nil?
      flash[:danger] = "Unable to find class type"
      redirect_to root_path
    end
  end

  def create_params
    params.require(:clazz_type).permit(ClazzType::PERMITTED_PARAMS)
  end
end

app/helpers/clazz_types_helper.rb
module ClazzTypesHelper
  def clazz_type_options
    make_clazz_type_options all_clazz_types
  end

  def not_class_template_class_type_options class_template
    make_clazz_type_options(all_clazz_types - class_template.clazz_types)
  end

  def class_template_class_type_options class_template
    make_clazz_type_options class_template.clazz_types
  end

  private

  def all_clazz_types
    ClazzType.all.order name: :asc
  end

  def make_clazz_type_options clazz_types
    clazz_types.map do |clazz_type|
      [clazz_type.name, clazz_type.id]
    end
  end
end

app/views/admin/clazz_types/_class_template_form_fields.html.haml
= f.hidden_field :clazz_type_id, value: @clazz_type.id
.form-group
  = f.select :class_template_id, not_clazz_type_class_template_options(@clazz_type), { include_blank: true }, class: "form-control"
.form-actions
  = f.submit "Add Class Template", class: "btn btn-primary"

app/views/admin/clazz_types/_class_templates_list.html.haml
- if @clazz_type.class_template_class_types.any?
  %ul.list-group
    - sorted_records(@clazz_type.class_template_class_types, :class_template_name).each do |class_template_class_type|
      %li.list-group-item
        = link_to class_template_class_type.class_template_name, edit_admin_class_template_path(class_template_class_type.class_template)
        = link_to "Remove", admin_class_template_class_type_path(class_template_class_type), method: :delete, class: "btn btn-danger btn-xs pull-right"

app/views/admin/clazz_types/_form_fields.html.haml
.form-group
  = f.label :name
  = f.text_field :name, autofocus: true, class: "form-control"
.form-actions
  = f.submit "Save", class: "btn btn-primary"

app/views/admin/clazz_types/edit.html.haml
= render partial: "shared/errors_for", locals: { object: @clazz_type }
%p
  = link_to admin_class_types_path, class: "btn btn-default" do
    %span
      %i.glyphicon.glyphicon-arrow-left
.panel.panel-default
  .panel-heading
    .panel-title< Class Type Details
  .panel-body
    = form_for @clazz_type, url: { action: :update} do |f|
      = render partial: "form_fields", locals: { f: f }
.panel.panel-default
  .panel-heading
    .panel-title< Associated Class Templates
  = render partial: "class_templates_list"
  .panel-footer
    = form_for :class_template_class_type, url: admin_class_template_class_types_path, method: :post do |f|
      = render partial: "class_template_form_fields", locals: { f: f }

app/views/admin/clazz_types/index.html.haml
%h3
  Class Types
  = link_to "Create", new_admin_class_type_path, class: "btn btn-primary btn-sm pull-right"
- if @clazz_types.any?
  %table.table
    %tbody
      - @clazz_types.each do |clazz_type|
        %tr
          %td= clazz_type.name
          %td= link_to "Edit", edit_admin_class_type_path(clazz_type), class: "btn btn-info btn-xs pull-right"
- else
  %p< No class types

app/views/admin/clazz_types/new.html.haml
= render partial: "shared/errors_for", locals: { object: @clazz_type }
= link_to admin_class_types_path, class: "btn btn-default" do
  %span
    %i.glyphicon.glyphicon-arrow-left
%h3< Create a Class Type
= form_for @clazz_type, url: { action: :create} do |f|
  = render partial: "form_fields", locals: { f: f }