config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: "users/registrations" },
             path_names: { sign_up: "" }

  root to: "home#home"
  get "random", to: "home#random_profile", as: :random_profile

  namespace :admin do
    resources :instructor_profiles, only: :index
    resources :class_types, except: [:show, :destroy], controller: :clazz_types
    resources :studios, except: [:show, :destroy]
    resources :studio_brands, except: [:show, :destroy]
    resources :studio_brand_studios, only: [:create, :destroy]
    resources :class_templates, except: [:show, :destroy]
    resources :class_template_class_types, only: [:create, :destroy]
    resources :invitations, only: [:index, :new, :create]
    resources :newsletter_signups, only: :index
    resource  :landing_page, only: [:edit, :update], controller: :landing_page
    resource :ghosting_session, only: [:create, :destroy]
  end

  resources :classes, only: [:show, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member

    resource :change, controller: :class_changes, only: [] do
      post :cancel
      post :uncancel
      post :substitute
      post :unsubstitute
      post :delete
      post :delete_and_future_weeks
    end
  end

  resources :recurring_classes, only: [:index, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member
  end

  resources :instructor_profiles, except: :destroy do
    get :welcome, on: :collection
    get :profile_photo
  end

  namespace :instructor_profile do
    resource :profile_photo, only: :edit
    resource :cover_photo, only: :edit
    resource :social_ids, only: :edit
  end

  resource :class_templates_by_studio, only: :show, controller: :class_templates_by_studio
  resource :duration_by_class_template, only: :show, controller: :duration_by_class_template

  resources :newsletter_signups, only: [:new, :create]
  resources :got_its, only: :create

  resource :search, only: :show, controller: :search

  get :faq, to: "home#faq", as: :faq

  get "robots.txt", to: "robots#show", controller: :robots

  get "/:id", to: "instructor_profiles#show", as: :profile
end

app/controllers/classes_controller.rb
class ClassesController < ClassesControllerBase
  before_action :find_clazz, except: [:new, :create]
  before_action :owns_clazz, except: [:new, :create, :show]

  def show
    @is_owner = owner?
    @clazz = @clazz.decorate
    NavbarConfig.instance.back_link = request.referer || profile_path(@clazz.instructor_profile.profile_path)
  end

  def new
    @clazz = Clazz.new
  end

  def create
    @clazz = current_user.instructor_profile.classes.create create_params
    if @clazz.valid?
      redirect_to confirm_class_path(@clazz)
    else
      @clazz = @clazz.decorate
      render :new
    end
  end

  def edit
    @clazz = @clazz.decorate
  end

  def update
    if @clazz.update_attributes create_params
      redirect_to confirm_class_path(@clazz)
    else
      @clazz = @clazz.decorate
      render :edit
    end
  end

  def confirm
    @clazz = @clazz.decorate
    NavbarConfig.instance.back_link = edit_class_path @clazz
  end

  def confirmed
    if @clazz.update_attributes confirmed: true
      flash[:success] = "Class created"
      redirect_to profile_path(current_user.instructor_profile.profile_path)
    else
      @clazz = @clazz.decorate
      render :edit
    end
  end

  private

  def find_clazz
    @clazz = clazz_scope.find_by id: params[:id]
    if @clazz.nil?
      flash[:danger] = "Unable to find class"
      redirect_to root_path
    end
  end

  def owner?
    user_signed_in? && current_user.id == @clazz.instructor_profile.user_id
  end

  def owns_clazz
    unless owner?
      flash[:danger] = "Unauthorized access"
      redirect_to root_path
    end
  end

  def clazz_scope
    if action_name == "show"
      Clazz.confirmed
    else
      Clazz.unconfirmed
    end
  end

  def create_params
    params.require(:clazz).permit(Clazz::PERMITTED_PARAMS)
  end
end

app/views/classes/_form_fields.html.haml
%li.list-group-item
  .row
    .col-xs-3.vcenter.class-info-key< Studio
    .col-xs-8.vcenter= f.select :studio_id, studio_options, { prompt: "Select the studio" }, class: "form-control input-xs", autofocus: true, id: "studio-select"
%li.list-group-item
  .row
    .col-xs-3.vcenter.class-info-key< Class
    .col-xs-8.vcenter
      - if f.object.studio
        = f.select :class_template_id, class_template_options(f.object.studio), {}, class: "form-control", id: "class-template-select"
      - else
        = f.select :class_template_id, [], {}, class: "form-control", id: "class-template-select", disabled: true
%li.list-group-item
  .row
    .col-xs-3.vcenter.class-info-key< Length (minutes)
    .col-xs-8.vcenter= f.number_field :duration, class: "form-control input-xs", id: "duration-text", disabled: f.object.duration.nil?
%li.list-group-item
  .row
    .col-xs-3.vcenter.class-info-key< Date
    .col-xs-8.vcenter= f.text_field :date, class: "form-control", id: "datepicker", readonly: true
%li.list-group-item
  .row
    .col-xs-3.vcenter.class-info-key< Time of Day
    .col-xs-8.vcenter= f.text_field :time_of_day, class: "form-control input-xs", id: "timepicker", readonly: true
%li.list-group-item
  .center
    = f.submit "Save", class: "btn btn-primary"
    = link_to "Cancel", profile_path(current_user.instructor_profile.profile_path), class: "btn btn-default"
%li.list-group-item
  .row
    .col-xs-12
      .alert.alert-info
        Don't see your class or studio?
        = mail_to contact_address, "Email us"

:javascript
  new ClassesByStudio();
  $(document).ready(function() {
    $('#datepicker').pickadate({
      today: "",
      clear: "",
      format: "yyyy-mm-dd",
      min: true,
      max: 180
    });
  });
  $(document).ready(function() {
    $('#timepicker').pickatime({
      clear: "",
      interval: 5,
      min: [5, 0],
      max: [22, 0],
      format: "hh:i A"
    });
  });

app/views/classes/_show_cancel.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< Cancel Class
  .panel-body
    %p< Click here to indicate on your schedule that the class has been canceled.
    = form_for :class_change, url: cancel_class_change_path(@clazz) do |f|
      = f.submit "Cancel Class", class: "btn btn-danger", data: { confirm: "Are you sure you want to cancel the class?" }

app/views/classes/_show_cancellation.html.haml
- if @clazz.canceled?
  = render partial: "show_uncancel"
- else
  = render partial: "show_cancel"

app/views/classes/_show_class_detail.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< The Sweat
  .panel-body= @clazz.description

app/views/classes/_show_delete.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< Delete Class
  .panel-body
    %p< Click the button to remove the meeting of:
    %p
      .class-detail= @clazz.name
      .class-detail= @clazz.studio_full_name
      %pan.class-detail
        = @clazz.display_date
        at
        = @clazz.display_time
    - if @clazz.recurring_class
      %p< Other meetings for this recurring class will not be affected.
    = form_for :class_change, url: delete_class_change_path(@clazz) do |f|
      = f.submit "Delete Class", class: "btn btn-danger", data: { confirm: "Are you sure you want to do this?" }

app/views/classes/_show_delete_recurring.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< Delete Recurring Class
  .panel-body
    %p< Click the button to make remove meetings of the recurring class:
    %p
      .class-detail= @clazz.name
      .class-detail= @clazz.studio_full_name
      %span.class-detail
        = @clazz.recurring_class.display_day_of_week
        at
        = @clazz.recurring_class.display_time
        on or after
        = @clazz.display_date
    %p
      Meetings for this recurring class before
      = @clazz.display_date
      will not be affected.
    = form_for :class_change, url: delete_and_future_weeks_class_change_path(@clazz) do |f|
      = f.submit "Delete Recurring Class", class: "btn btn-danger", data: { confirm: "Are you sure you want to do this?" }

app/views/classes/_show_deletion.html.haml
= render partial: "show_delete"
- if @clazz.recurring_class
  = render partial: "show_delete_recurring"

app/views/classes/_show_studio_detail.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< The Space
  .panel-body
    = render partial: "studio_address"
    = render partial: "studio_map"

app/views/classes/_show_substitution.html.haml
- if @clazz.substituted?
  = render partial: "show_unsubstitute"
- else
  = render partial: "show_substitute"

app/views/classes/_show_summary.html.haml
.section.class-summary
  .class-name= @clazz.name
  .studio-full-name= @clazz.studio_full_name
  %div= @clazz.display_long_date
  %div
    = @clazz.display_time
    for
    = @clazz.display_duration
  - unless @clazz.recurring_class
    .one-time-class< Not part of instructor's regular schedule

app/views/classes/_studio_map.html.haml
.studio-map
  = link_to @clazz.studio.map_url, target: "_blank" do
    = image_tag @clazz.studio.map_preview_url

app/views/classes/confirm.html.haml
= render partial: "shared/errors_for", locals: { object: @clazz }
.panel.panel-default
  .panel-heading
    .panel-title< Please confirm these details
  %ul.list-group
    = form_for @clazz, url: confirmed_class_path(@clazz), method: :patch do |f|
      %li.list-group-item
        .row
          .col-xs-3.class-info-key< Studio
          .col-xs-8= @clazz.studio_full_name
      %li.list-group-item
        .row
          .col-xs-3.class-info-key< Class
          .col-xs-8= @clazz.name
      %li.list-group-item
        .row
          .col-xs-3.class-info-key< Length
          .col-xs-8= @clazz.display_duration
      %li.list-group-item
        .row
          .col-xs-3.class-info-key< Date
          .col-xs-8= "#{@clazz.display_day_of_week} #{@clazz.display_date}"
      %li.list-group-item
        .row
          .col-xs-3.class-info-key< Time
          .col-xs-8= @clazz.display_time
      %li.list-group-item
        .center
          = f.submit "Confirm", class: "btn btn-primary"
          = link_to "Cancel", profile_path(current_user.instructor_profile.profile_path), class: "btn btn-default"

app/views/classes/edit.html.haml
= render partial: "shared/errors_for", locals: { object: @clazz }
.panel.panel-default
  .panel-heading
    .panel-title< Create a one-time class
  %ul.list-group
    = form_for @clazz, url: class_path(@clazz), method: :patch do |f|
      = render partial: "form_fields", locals: { f: f }

app/views/classes/new.html.haml
= render partial: "shared/errors_for", locals: { object: @clazz }
.panel.panel-default
  .panel-heading
    .panel-title< Create a one-time class
  %ul.list-group
    = form_for @clazz, url: { action: :create } do |f|
      = render partial: "form_fields", locals: { f: f }