config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: "users/registrations" },
             path_names: { sign_up: "" }

  root to: "home#home"
  get "random", to: "home#random_profile", as: :random_profile

  namespace :admin do
    resources :instructor_profiles, only: :index
    resources :class_types, except: [:show, :destroy], controller: :clazz_types
    resources :studios, except: [:show, :destroy]
    resources :studio_brands, except: [:show, :destroy]
    resources :studio_brand_studios, only: [:create, :destroy]
    resources :class_templates, except: [:show, :destroy]
    resources :class_template_class_types, only: [:create, :destroy]
    resources :invitations, only: [:index, :new, :create]
    resources :newsletter_signups, only: :index
    resource  :landing_page, only: [:edit, :update], controller: :landing_page
    resource :ghosting_session, only: [:create, :destroy]
  end

  resources :classes, only: [:show, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member

    resource :change, controller: :class_changes, only: [] do
      post :cancel
      post :uncancel
      post :substitute
      post :unsubstitute
      post :delete
      post :delete_and_future_weeks
    end
  end

  resources :recurring_classes, only: [:index, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member
  end

  resources :instructor_profiles, except: :destroy do
    get :welcome, on: :collection
    get :profile_photo
  end

  namespace :instructor_profile do
    resource :profile_photo, only: :edit
    resource :cover_photo, only: :edit
    resource :social_ids, only: :edit
  end

  resource :class_templates_by_studio, only: :show, controller: :class_templates_by_studio
  resource :duration_by_class_template, only: :show, controller: :duration_by_class_template

  resources :newsletter_signups, only: [:new, :create]
  resources :got_its, only: :create

  resource :search, only: :show, controller: :search

  get :faq, to: "home#faq", as: :faq

  get "robots.txt", to: "robots#show", controller: :robots

  get "/:id", to: "instructor_profiles#show", as: :profile
end

app/models/instructor_profile.rb
class InstructorProfile < ActiveRecord::Base
  include Elasticsearch::Model

  PERMITTED_PARAMS = [
    "profile_path",
    "user_id",
    "profile_photo",
    "remove_profile_photo",
    "cover_photo",
    "remove_cover_photo",
    "facebook",
    "instagram",
    "spotify",
    "youtube",
    "twitter",
  ]

  validates_presence_of :profile_path
  validates_uniqueness_of :profile_path
  validates_format_of :profile_path, with: /\A([a-zA-Z]|\d)+(\-([a-zA-Z]|\d)+)*\z/
  belongs_to :user
  has_many :class_templates, through: :classes
  has_many :classes, class_name: "Clazz", dependent: :destroy
  has_many :recurring_classes, dependent: :destroy
  acts_as_paranoid
  has_paper_trail
  mount_uploader :cover_photo, CoverPhotoUploader
  validates :cover_photo,
            file_size: { less_than: 10.megabytes }
  mount_uploader :profile_photo, ProfilePhotoUploader
  validates :profile_photo,
            file_size: { less_than: 10.megabytes }
  scope :searchable, -> { where "non_searchable IS NULL OR non_searchable != 't'" }

  def as_indexed_json options = {}
    self.as_json(only: [:id, :profile_path, :facebook, :instagram, :youtube, :twitter, :spotify])
      .merge(name: user.name)
  end

  after_commit on: [:create] do
    __elasticsearch__.index_document unless non_searchable?
  end

  after_commit on: [:update] do
    if previous_changes[:non_searchable]
      if non_searchable?
        __elasticsearch__.delete_document
      else
        __elasticsearch__.index_document
      end
    else
      __elasticsearch__.update_document unless :non_searchable?
    end
  end

  after_commit on: [:destroy] do
    __elasticsearch__.delete_document unless non_searchable?
  end
end

app/controllers/admin/instructor_profiles_controller.rb
class Admin::InstructorProfilesController < Admin::ControllerBase
  def index
    @instructor_profiles = InstructorProfile.order(:profile_path).decorate
    @count = @instructor_profiles.count
  end
end

app/controllers/instructor_profile/base_controller.rb
class InstructorProfile::BaseController < ApplicationController
  before_action :user_signed_in
  before_action :user_has_profile
  before_action :set_back_link

  def edit
    @instructor_profile = current_user.instructor_profile.decorate
  end

  private

  def set_back_link
    NavbarConfig.instance.back_link = profile_path current_user.instructor_profile.profile_path
  end
end

app/controllers/instructor_profile/cover_photos_controller.rb
class InstructorProfile::CoverPhotosController < InstructorProfile::BaseController
end

app/controllers/instructor_profile/profile_photos_controller.rb
class InstructorProfile::ProfilePhotosController < InstructorProfile::BaseController
end

app/controllers/instructor_profile/social_ids_controller.rb
class InstructorProfile::SocialIdsController < InstructorProfile::BaseController
end

app/controllers/instructor_profiles_controller.rb
class InstructorProfilesController < ApplicationController
  before_action :user_signed_in, except: [:show, :profile_photo]
  before_action :user_does_not_have_profile, only: [:new, :create, :welcome]
  before_action :user_has_profile, except: [:show, :profile_photo, :new, :create, :welcome]
  before_action :find_instructor_profile, only: [:edit, :update, :destroy]
  before_action :owns_instructor_profile, only: [:edit, :update, :destroy]
  before_action :find_instructor_profile_by_name, only: [:show, :profile_photo]

  def show
    @classes_by_date = classes_by_date
    @date_range = date_range
    @presenter = InstructorClassesPresenter.new classes_by_date, date_range
    NavbarConfig.instance.new_class_button = owner?
    NavbarConfig.instance.profile_page = true
    @instructor_profile = @instructor_profile.decorate
  end

  def profile_photo
    @instructor_profile = @instructor_profile.decorate
  end

  def new
    @instructor_profile = InstructorProfile.new profile_path: current_user.name.downcase.gsub(" ", "")
  end

  def edit
  end

  def create
    @instructor_profile = current_user.build_instructor_profile create_params
    if @instructor_profile.save
      redirect_to profile_path(@instructor_profile.profile_path)
    else
      render :new
    end
  end

  def update
    unless @instructor_profile.update_attributes create_params
      flash[:danger] = @instructor_profile.errors.full_messages.first
    end
    redirect_to profile_path(@instructor_profile.profile_path)
  end

  def welcome
  end

  private

  def assert_instructor_profile
    if @instructor_profile.nil?
      flash[:danger] = "Unable to find instructor profile"
      redirect_to root_path
    end
  end

  def find_instructor_profile
    @instructor_profile = InstructorProfile.find_by id: params[:id]
    assert_instructor_profile
  end

  def find_instructor_profile_by_name
    @instructor_profile = InstructorProfile.find_by profile_path: (params[:id] || params[:instructor_profile_id])
    assert_instructor_profile
  end

  def owner?
    user_signed_in? && current_user.id == @instructor_profile.user_id
  end

  def owns_instructor_profile
    unless owner?
      flash[:danger] = "Unauthorized access"
      redirect_to root_path
    end
  end

  def create_params
    if params.has_key? :instructor_profile
      params.require(:instructor_profile).permit(InstructorProfile::PERMITTED_PARAMS)
    else
      {}
    end
  end

  def classes_by_date
    @classes_by_date ||=
      begin
        classes.each_with_object({}) do |clazz, classes_by_date|
          (classes_by_date[clazz.date] ||= []).push clazz
        end
      end
  end

  def classes
    @classes ||= @instructor_profile.classes.confirmed.includes([:studio, :class_template])
      .order(timestamp: :asc)
      .where(timestamp: date_range.range).decorate
  end

  def date_range
    @date_range ||= DateRange.new current_user, params[:start_date]
  end
end

app/helpers/instructor_profiles_helper.rb
module InstructorProfilesHelper
  def profile_prev_page_path instructor_profile, date_range
    profile_path instructor_profile.profile_path,
                 start_date: date_range.prev_start_date
  end

  def profile_next_page_path instructor_profile, date_range
    profile_path instructor_profile.profile_path,
                 start_date: date_range.next_start_date
  end

  def social_link site, instructor_profile, &block
    path = @instructor_profile.send("#{site}_link")
    options = {
      class: "btn btn-social-icon btn-#{site}",
      target: "_blank"
    }
    link_to path, options do
      block.call
    end
  end
end

app/views/instructor_profile/social_ids/_form.html.haml
= form_for @instructor_profile, url: instructor_profile_path(@instructor_profile), method: :patch do |f|
  %li.list-group-item
    .alert.alert-info
      Complete the URLs for the profiles you want to link to.
  %li.list-group-item
    .row
      .col-xs-offset-3.col-xs-9
        .social-url-example
          .stem#facebook-label= @instructor_profile.facebook_stem
    .row
      .col-xs-3.vcenter.class-info-key< Facebook
      .col-xs-8.vcenter= f.text_field :facebook, class: "form-control", id: "facebook-input"
  %li.list-group-item
    .row
      .col-xs-offset-3.col-xs-9
        .social-url-example
          .stem#instagram-label= @instructor_profile.instagram_stem
    .row
      .col-xs-3.vcenter.class-info-key< Instagram
      .col-xs-8.vcenter= f.text_field :instagram, class: "form-control", id: "instagram-input"
  %li.list-group-item
    .row
      .col-xs-offset-3.col-xs-9
        .social-url-example
          .stem#spotify-label= @instructor_profile.spotify_stem
    .row
      .col-xs-3.vcenter.class-info-key< Spotify
      .col-xs-8.vcenter= f.text_field :spotify, class: "form-control", id: "spotify-input"
  %li.list-group-item
    .row
      .col-xs-offset-3.col-xs-9
        .social-url-example
          .stem#twitter-label= @instructor_profile.twitter_stem
    .row
      .col-xs-3.vcenter.class-info-key< Twitter
      .col-xs-8.vcenter= f.text_field :twitter, class: "form-control", id: "twitter-input"
  %li.list-group-item
    .row
      .col-xs-offset-3.col-xs-9
        .social-url-example
          .stem#youtube-label= @instructor_profile.youtube_stem
    .row
      .col-xs-3.vcenter.class-info-key< Youtube
      .col-xs-8.vcenter= f.text_field :youtube, class: "form-control", id: "youtube-input"
  %li.list-group-item.center
    = f.submit "Update", class: "btn btn-primary", data: { disable_with: "Please wait..." }
:javascript
  new InputLabelKeyMatcher("#facebook-input", "#facebook-label", "hello");
  new InputLabelKeyMatcher("#instagram-input", "#instagram-label", "hello");
  new InputLabelKeyMatcher("#spotify-input", "#spotify-label", "hello");
  new InputLabelKeyMatcher("#twitter-input", "#twitter-label", "hello");
  new InputLabelKeyMatcher("#youtube-input", "#youtube-label", "hello");

app/views/instructor_profile/social_ids/edit.html.haml
.panel.panel-default
  .panel-heading
    .panel-title< Update Social Links
  .panel-body
    = render partial: "form"