config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             controllers: { registrations: "users/registrations" },
             path_names: { sign_up: "" }

  root to: "home#home"
  get "random", to: "home#random_profile", as: :random_profile

  namespace :admin do
    resources :instructor_profiles, only: :index
    resources :class_types, except: [:show, :destroy], controller: :clazz_types
    resources :studios, except: [:show, :destroy]
    resources :studio_brands, except: [:show, :destroy]
    resources :studio_brand_studios, only: [:create, :destroy]
    resources :class_templates, except: [:show, :destroy]
    resources :class_template_class_types, only: [:create, :destroy]
    resources :invitations, only: [:index, :new, :create]
    resources :newsletter_signups, only: :index
    resource  :landing_page, only: [:edit, :update], controller: :landing_page
    resource :ghosting_session, only: [:create, :destroy]
  end

  resources :classes, only: [:show, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member

    resource :change, controller: :class_changes, only: [] do
      post :cancel
      post :uncancel
      post :substitute
      post :unsubstitute
      post :delete
      post :delete_and_future_weeks
    end
  end

  resources :recurring_classes, only: [:index, :new, :create, :edit, :update] do
    get :confirm, on: :member
    patch :confirmed, on: :member
  end

  resources :instructor_profiles, except: :destroy do
    get :welcome, on: :collection
    get :profile_photo
  end

  namespace :instructor_profile do
    resource :profile_photo, only: :edit
    resource :cover_photo, only: :edit
    resource :social_ids, only: :edit
  end

  resource :class_templates_by_studio, only: :show, controller: :class_templates_by_studio
  resource :duration_by_class_template, only: :show, controller: :duration_by_class_template

  resources :newsletter_signups, only: [:new, :create]
  resources :got_its, only: :create

  resource :search, only: :show, controller: :search

  get :faq, to: "home#faq", as: :faq

  get "robots.txt", to: "robots#show", controller: :robots

  get "/:id", to: "instructor_profiles#show", as: :profile
end

app/views/layouts/navigation/_admin.html.haml
%li.mm-divider< Admin
%li.menu-link= link_to "Manage Instructor Profiles", admin_instructor_profiles_path
%li.menu-link= link_to "Manage Class Types", admin_class_types_path
%li.menu-link= link_to "Manage Studio Brands", admin_studio_brands_path
%li.menu-link= link_to "Manage Studios", admin_studios_path
%li.menu-link= link_to "Manage Class Templates", admin_class_templates_path
%li.menu-link= link_to "Manage Invitations", admin_invitations_path
%li.menu-link= link_to "Manage Newsletter Subscriptions", admin_newsletter_signups_path
%li.menu-link= link_to "Manage Landing Page", edit_admin_landing_page_path

app/views/layouts/navigation/_back_link.html.haml
- if @navbar.back_link
  = link_to @navbar.back_link do
    %span.navbar-brand
      %i.glyphicon.glyphicon-chevron-left

app/views/layouts/navigation/_ghosting.html.haml
%p.navbar-text.ghosting-as
  Ghosting as:
  = current_user.name
= link_to "End", admin_ghosting_session_path, method: :delete, class: "btn btn-sm navbar-btn btn-success pull-right"

app/views/layouts/navigation/_menu_data.html.haml
%nav#my-menu
  %ul
    - if user_signed_in?
      = render partial: "layouts/navigation/signed_in_user"
      - if current_user.admin?
        = render partial: "layouts/navigation/admin"
    - else
      = render partial: "layouts/navigation/signed_out_user"

app/views/layouts/navigation/_menu_dropdown.html.haml
- if @navbar.needs_menu_dropdown?
  = link_to "#", class: "navbar-brand", id: "menu-hamburger" do
    SweatSpace
    %span.caret

app/views/layouts/navigation/_primary_nav.html.haml
%nav.navbar.navbar-default#primary-nav
  .container-fluid
    = render partial: "layouts/navigation/back_link"
    = render partial: "layouts/navigation/menu_dropdown"
    = render partial: "layouts/navigation/search_button"
    = render partial: "layouts/navigation/menu_data"

:javascript
  $(function() {
    $("#my-menu").mmenu();
  });
  $("#menu-hamburger").click(function() {
    $("#my-menu").data("mmenu").open();
  });

app/views/layouts/navigation/_random_profile_button.html.haml
= link_to random_profile_path, class: "btn btn-danger btn-sm navbar-btn pull-right" do
  %span
    %i.glyphicon.glyphicon-flash

app/views/layouts/navigation/_search_button.html.haml
%form.narrow-search
  .form-group#narrow-search-text
    %span
      %i.glyphicon.glyphicon-search
    = text_field_tag :text, "", class: "form-control", placeholder: "Search", readonly: true

app/views/layouts/navigation/_search_nav.html.haml
%nav.navbar.navbar-default#search-nav
  .container-fluid
    %span.navbar-brand#search-back-link
      %i.glyphicon.glyphicon-chevron-left
    %form.wide-search
      .form-group
        %span
          %i.glyphicon.glyphicon-search
        = text_field_tag :text, "", class: "form-control", placeholder: "Search", id: "search-text", autocomplete: "off"
  .panel#search-popout
    %ul.list-group#search-list

app/views/layouts/navigation/_signed_in_user.html.haml
- if current_user.instructor_profile
  %li.menu-link= link_to "Home", home_path
- else
  %li.menu-link= link_to "Home", welcome_instructor_profiles_path
%li.menu-link= link_to "FAQ", faq_path
%li.menu-link= link_to "Log Out", destroy_user_session_path, method: :delete

app/views/layouts/navigation/_signed_out_user.html.haml
%li.menu-link= link_to "Home", home_path
%li.menu-link= link_to "FAQ", faq_path
%li.menu-link= link_to "Instructor Log In", new_user_session_path

app/views/layouts/navigation/_user.html.haml
%li.mm-divider< User
%li.menu-link= link_to "My Account", edit_registration_path(current_user)
%li.menu-link= link_to "Log Out", destroy_user_session_path, method: :delete
%li.mm-divider< Profile
- if current_user.instructor_profile.try :persisted?
  %li.menu-link= link_to "View Profile", profile_path(current_user.instructor_profile.profile_path)
  %li.menu-link= link_to "Edit Profile", edit_instructor_profile_path(current_user.instructor_profile)
- else
  %li.menu-link= link_to "Create Profile", new_instructor_profile_path